spring:
  application:
    name: credentialsgenerator

  config:
    import: classpath:app.yaml

server:
  port: '${CREDENTIALS_GENERATOR_PORT:8080}'
  servlet:
    context-path: '/api'
  address: 0.0.0.0